#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const webpack = require('webpack');
const config = require('../config/webpack.config.js');

async function build() {
  return new Promise((resolve, reject) => {
    webpack(config, (err, stats) => {
      if (err) {
        console.error('❌ Błąd webpack:', err);
        process.exit(1);
      }

      if (stats.hasErrors()) {
        console.error('❌ Errory webpack:');
        console.error(stats.toString());
        process.exit(1);
      }

      const bundledPath = path.join(__dirname, '../build', 'bookmarklet-bundled.js');
      let bundledCode = fs.readFileSync(bundledPath, 'utf8');

      // Webpack już obudował kod w IIFE
      bundledCode = extractBrowserCode(bundledCode);

      // Dodaj javascript: prefix
      const bookmarklet = `javascript:${bundledCode}`;

      // Zapis do pliku
      const outputPath = path.join(__dirname, '../build', 'bookmarklet.txt');
      fs.writeFileSync(outputPath, bookmarklet, 'utf8');

      console.log('✓ Bookmarklet został wygenerowany!');
      console.log(`✓ Plik: ${outputPath}`);
      console.log(`✓ Rozmiar: ${bookmarklet.length} znaków`);
      console.log('✓ Obsługa: IE11+ i starsze przeglądarki');
      console.log('✓ Zabudowana biblioteka: lodash.deburr\n');

      resolve();
    });
  });
}

/**
 * Ekstrahuj kod przeglądarki z bundle
 */
function extractBrowserCode(code) {
  // Webpack z iife: true generuje coś takiego:
  // !function(){...code...}()

  // Usuń "use strict"; na początek
  code = code.replace(/^"use strict";/, '');

  // IIFE already generated by webpack, just return as is
  return code;
}

build().catch((error) => {
  console.error('❌ Błąd budowania:', error.message);
  process.exit(1);
});
